# Generated by Django 5.2.15 on 2026-10-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CLOCK_IN', 'Arrival / Clock-In SMS'), ('FEE_REMINDER', 'Fee Arrears Reminder')], max_length=20)),
                ('recipient', models.CharField(default='Parent / Guardian', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.student')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'School Administrator'), ('TEACHER', 'Teacher'), ('ACCOUNTANT', 'Accountant / Bursar')], default='TEACHER', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('assigned_class', models.CharField(blank=True, help_text='Specific class for class teacher (optional)', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
