# Generated by Django 5.2.15 on 2026-10-05 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_notificationlog_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Class 1A', 'Class 2B', 'Nursery 1'", max_length=50, unique=True)),
                ('grade_level', models.CharField(blank=True, help_text='Optional level group (e.g. Primary, JHS, Kindergarten)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Active classes appear in fee recording and attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.schoolclass'),
        ),
    ]
