# Generated by Django 5.2.17 on 2026-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_schoolsetting_alter_feepayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_collect_fees',
            field=models.BooleanField(default=False, help_text='Designates whether this teacher is authorized to record and collect fee payments.'),
        ),
    ]
