# Generated by Django 5.2.17 on 2026-10-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_userprofile_can_collect_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='bus',
            field=models.ForeignKey(blank=True, help_text='Specific bus route this fee payment was collected on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='attendance.bus'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='is_temporary_bus',
            field=models.BooleanField(default=False, help_text='True if recorded for a one-off/guest bus ride different from student regular route'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_bus',
            field=models.ForeignKey(blank=True, help_text='Specific bus route for bus teacher/conductor (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='attendance.bus'),
        ),
    ]
