# Generated by Django 5.2.17 on 2026-10-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_feepayment_bus_feepayment_is_temporary_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='days_covered',
            field=models.PositiveIntegerField(default=1, help_text='Number of school days this payment is intended to cover'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='is_advance',
            field=models.BooleanField(default=False, help_text='True if recorded as advance payment covering future days'),
        ),
    ]
